name: 'Build and deploy Python app to Azure Web App: formitvalleybackend'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create virtual environment and install dependencies
      working-directory: backend
      run: |
        python -m venv antenv
        source antenv/bin/activate
        pip install -r requirements.txt

    - name: Zip deploy package
      working-directory: backend
      run: zip -r deploy.zip . -x "venv/*" "__pycache__/*" "*.pyc"

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'formitvalleybackend'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
        package: backend/deploy.zip
